### ISSUE TITLE
N2 .Search function doesn't work properly, as its actually a Filter, and it only filters loaded ads, through scrolling down, its not searching for ads inside the database

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#1]
the search bar doesn’t do its job at all, try to search for « Android » for example, it doesn’t show the Android Ad posted. Also, try to search for something like « wwwsss » it will still display ads.

**Comment by sudiptaExicube** [comment]
*** Search work properly, and also searching for ads inside the database
![productdata](https://user-images.githubusercontent.com/20201253/36372894-7dbbee56-158c-11e8-8f12-6a62245c0703.png)
![searchresult](https://user-images.githubusercontent.com/20201253/36372897-7df9eeea-158c-11e8-9265-dc4e00d7f997.PNG)

**Comment by spunlock** [comment]
is it done on actual live deployment of the app ? 
or should I update the app to newer version to see the changes ?

**Comment by codersudipta** [comment]
This is supposed to be working on the last version sent to you.

**Comment by spunlock** [comment]
WIll the search function works when there will be thousands of Ads inside the App. 
As now, the speed to wich it displays the Ads, is just like its not doing any DB query !!!

**Comment by spunlock** [comment]
Hello, 
Can you please answer my pending question ? 
Thanks in advance

**Comment by codersudipta** [comment]
It is obvious, it is fetching from database.  When the Ads will increase, the loading spinner will take a little long.
