### ISSUE TITLE
N14. I still can't check the app with the second iOS device, (iPhone 6)

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#10]
please provide  UDID of your 2nd Device

**Comment by spunlock** [comment]
Here is the UDID of second iOS device (iphone 6) 
BFED376B24C603AB0C34E828D29A634C69040353 

Please provide new App for this device, if app still doens't work, I'll provide a video capture of the issue. 

Thanks

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
Solved, MANY THANKS  !!!
