### ISSUE TITLE
N15. Left arrow, back icon, when on Ad Page, is aligned to the absolute top, on iOS, so its very difficult to click on it, to go back, please align it

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#11]
Okey i will check it

**Comment by spunlock** [comment]
Here is the issue, arrow is displayed very high, I can't click on it easily 




![n15](https://user-images.githubusercontent.com/11454643/36822130-c06e45a2-1cf6-11e8-8f19-74fe2c7deafd.gif)

**Comment by spunlock** [comment]
Still not solved on my end !

**Comment by sudiptaExicube** [comment]
solve will be update in next Release

**Comment by spunlock** [comment]
Still not solved !!!

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
Fixed, Thanks !
