### ISSUE TITLE
N18. Sort listings by distance, price, or post date.

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#12]
Although it works fine but i will check it again

**Comment by spunlock** [comment]
Filtering by date doesn't work good 
when we pick : _Oldest_, it gives Ads in right order, however for _Newest_, things are a little messed up. 
Please give it a try with : 
Category : Books & Hobbies  (no sub category filtering) 
Filter by : Newest 
Then Check the order of the displayed ads, 
-
Or, from DISCOVER tab, click filter, and without touching anything slide down to : Filter by, and pick "Newest", you will see order of newest Ads, isn't RIGHT

–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

**Distance Filtering** _doesn't work_, if you add to it , Filter by "Newest / Oldest"

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
This issue is still not solved : 
**1. Date filter issue**
- Click on Filter icon (funel) , 
- Head down to Sort by Date, and select : Newest 
- It will display Ads in a wrong order 

**2. Distance Filter issue**
- Open filter, 
- Select radius for example 2000 km 
- Sort by Newest / oldest 
- You will see all Ads, even mine (which are far far away, than 2000km)

**Comment by codersudipta** [comment]
1. Everything seems fine to me. I have checked the timestamps of each Ad in the newest.
2. Newest ad Oldest will order all Ads with respect to the timestamps. You Ads will come for your location.

**Comment by spunlock** [comment]
"Discover Tab" is obviously showing Ads in "Newest" Order, and as radius has been changed to 15000km, its showing all the Ads of the world. Right ? 
So, 
- when I first open the app, end up in "Discover Tab" , 
- I hit Filter, and selects, order by "Newest" 
- I then see a completely different order in the Ads, than the one I saw before ! 
old ads get before recent ones,
 
Please bro, just give it a try, using this flow. 

Best,

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
Fixed, Thanks !
