### ISSUE TITLE
N23. Reset category filtering, doesn't work

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#17]
![reset filter](https://user-images.githubusercontent.com/20201253/36376710-126fd7a8-159a-11e8-9c75-3bbcb87b6658.PNG)

It working from Before

**Comment by spunlock** [comment]
My bad, I meant Sorting ! 
Reset the Categories Sorting isn't working. I can't go back to display listings from **All Cateogires**

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
Fixed, Thanks, !!!
