### ISSUE TITLE
N24. From Ad page, If click on chat icon, Chat starts, and When I click on top right profile picture , I get send to my profile page, instead of Other person's profile page, and I'm stuck there, as there is no back icon

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#19]
There have some small issue i will will fix it

**Comment by sudiptaExicube** [comment]
Done

**Comment by spunlock** [comment]
is it done on actual live deployment of the app ? 
or should I update the app to newer version to see the changes ?

**Comment by codersudipta** [comment]
This will be sent on you the new version. It is updated as done to inform you that I am working on this and solved it. Will send these points together laster in the new version.

**Comment by spunlock** [comment]
Solved ! Thank you !
