### ISSUE TITLE
N3 . Filtering results by price / categories, doesn't work

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#2]
When you filter ads by category, (btw, what only works now, is filtering by category named « Fashion », try filter by Mobile or Electronic Appliance, then nothing will show) , it displays an ad related to that category, however, if you slide down, it will load ads from Categories, that aren’t related to Filtered category at all. 

![filterby electronics](https://user-images.githubusercontent.com/20201253/36371393-f532afce-1587-11e8-9cc8-b569169c50c2.PNG)

![searchresult](https://user-images.githubusercontent.com/20201253/36371411-056e742c-1588-11e8-9dfc-00fa311ff3c3.PNG)

**Comment by sudiptaExicube** [comment]
Done

**Comment by spunlock** [comment]
is it done on actual live deployment of the app ? 
or should I update the app to newer version to see the changes ?

**Comment by codersudipta** [comment]
This is supposed to be working on the last version sent to you.

**Comment by spunlock** [comment]
Working ! Thanks !!!
