### ISSUE TITLE
N0. The Pinterest Ads bricks effect, is no more there

### ISSUE THREAD

**Issue by spunlock** [codersudipta/EcomIssues#24]
This was one of the main reason why we choosed that ionic template, for that cool pinterest bricks effect, but its not there anymore !

**Comment by spunlock** [comment]
Here is what I'm talking about 
![n0](https://user-images.githubusercontent.com/11454643/36821740-cb72a508-1cf4-11e8-8223-11223c66afb7.PNG)

**Comment by spunlock** [comment]
Here is the Pinterest-like UI, we want to have (screen shot taken from the template we're using for the app)

![n0](https://user-images.githubusercontent.com/11454643/36822156-daadb93e-1cf6-11e8-9d2d-977d4cea22a0.gif)

**Comment by spunlock** [comment]
Anything here ?

**Comment by spunlock** [comment]
How can Ads have no squared images, for the Pinterest effect to be there ?! 
As I tested and posted some Ads, and all their images get squared by the "Square crop" tool.

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
AWESOME work, Thanks !
