### ISSUE TITLE
N33. Sorting Ads by Categories

### ISSUE THREAD

**Issue by spunlock** [codersudipta/EcomIssues#29]
When I click the "arrow down" icon, from DISCOVER tab, and select any of the categories, 
The app shows a Loading pop up, and stays there forever. 

I tried this many times, with all the Categories.

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
This still doesn't work at my end, 90% of available categories, show Blank result, while they're having Ads inside.
I can provide a video tomorrow, to demonstrate that.

**Comment by spunlock** [comment]
Here is the video :  https://drive.google.com/open?id=1OTf1wt5qGx8BOgFft-3-USznOysf8hjb

**Comment by spunlock** [comment]
Can't you make it as Asked here ? 
https://github.com/codersudipta/EcomIssues/issues/8
This is a simple page, with list of categories, leading to subcategories (if any)

**Comment by spunlock** [comment]
Nice work on it, 
Just please make the drop down PopUp : 
- A little bigger, so we can click easily on categories (they're too close now)
- Add first element in all the sub-categories list called : **All in {{the parent category}}**

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
Solved, MANY THANKS  !!!
