### ISSUE TITLE
N5. Can't zoom on images, (once we open them)

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#3]
It works Fine 

This is Normal View
![photo](https://user-images.githubusercontent.com/20201253/36371629-b225abae-1588-11e8-8c9a-536c86b62b63.PNG)

This is Zoom View
![zoomview](https://user-images.githubusercontent.com/20201253/36371630-b26c5540-1588-11e8-89a0-904b0047ed7e.PNG)

**Comment by sudiptaExicube** [comment]
It Works Now

**Comment by spunlock** [comment]
is it done on actual live deployment of the app ? 
or should I update the app to newer version to see the changes ?

**Comment by codersudipta** [comment]
This is supposed to be working on the last version sent to you.

**Comment by spunlock** [comment]
I do have last version, and still this doesn't work, please see the video below : 
https://s3-us-west-2.amazonaws.com/chadmadi-app/N5.mov

**Comment by spunlock** [comment]
Very good, Thanks !
