### ISSUE TITLE
N34. Ads ordering inside MY ADS tab, should be reversed

### ISSUE THREAD

**Issue by spunlock** [codersudipta/EcomIssues#30]
Same as it was on DISCOVER TAB, the Ads inside "My ADS" (SELLING / SOLD / FAVOURITES) are showing from Oldes to Newest, while they should be showing Newest Ads first !

**Comment by sudiptaExicube** [comment]
Solved. Will Be Updated in Next Release

**Comment by sudiptaExicube** [comment]
solve will be update next milestone

**Comment by spunlock** [comment]
Fixed, Thanks !
