### ISSUE TITLE
N6.image crop doesnt work properly for pictures taken by Camera (not those taken from Gallery Album), as we can't move the square, nor the image

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#4]
It already works
![screenshot_20180219-155805](https://user-images.githubusercontent.com/20201253/36373435-267f8f88-158e-11e8-8f31-3fadf5ae8400.png)

**Comment by spunlock** [comment]
I was able to see this cropping square only on this latest update (05 march). 
Very well done, thanks. 
However, the cropped image, once used, takes from 30 sec to 60 sec, to load up inside the Ad submitting form, there's obviously an issue with it. Before, images were loading quickly.

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
Still the uploading of the picture takes way too long, minimum is 20 to 30 sec, to see the small thumbnail showing (when on Ad posting form), this can't take that long. 

This is a core utility feature of the app, the ease of posting Ads from a mobile phone, if it takes that long (+30sec / picture, means, arroung 2mins for 4 pictures) it takes off all the purpose of using the App. 

Also on other Classified apps we've checked, taking pictures is a breeze, from Taking picture and submitting the Ad is almost instant !

Please check this up,

**Comment by sudiptaExicube** [comment]
Solved. Will Be Updated in Next Release

**Comment by spunlock** [comment]
Thanks, 
Hope I can get the app today (saturday 10 march)

**Comment by spunlock** [comment]
Adding pictures by camera still takes between 30 to 40 secs, 
however, when adding them from Library, only takes 2 to 3 secs max. 
Please consider this information, to fix the image upload time issue (from camera)

**Comment by sudiptaExicube** [comment]
https://drive.google.com/file/d/1mN4fYoMLcfSgkknDSIM2aoST0A7dHQN_/view

**Comment by spunlock** [comment]
I tried to post an Ad, using that 2nd iOS device, image upload from Camera, took from 40 to 65 secs,image upload from Library (2secs) , if it was internet speed, it would have took same amount of time, as both images where captured by phone camera, so approx same size.

I would love to see the image upload by camera, at your end, from a Live video call here on upwork, to see that its different than how it is at my end. just let me know when we can do so

**Comment by spunlock** [comment]
Fixed, Thanks !
