### ISSUE TITLE
N8 . Adding item to Favourite, using Heart icon, doesn't work, I can't find ads, inside My ADS / FAVOURITES

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#6]
*** “Heart” icon is for Like Product. 
*** For “add to Favorite” you just click to the “Star” icon, and your product added to favorite.
![favourite1](https://user-images.githubusercontent.com/20201253/36374401-3ca09ef8-1591-11e8-8cb4-df8afba9af84.png)

**Comment by spunlock** [comment]
So this STAR icon should be inside the Ad Page too, (besides Chat icon), so I will be able to Add to Favourite, other Sellers Ads to my Favourites TAB, instead of how it is now, only adding my OWN Ads to Favourite. 
Thanks

**Comment by spunlock** [comment]
Great ! The Ads are now added to my Favourites Tab. 
However, the UI is buggy. 
- When you click on "outlined star", you see a big Ping circle surrounding it. 
- After "outlined star" is clicked, it doesn't become "Plain star"
- Notification from top "Ad was added to favourite" doesn't show up. (it only shows when I add to favourite my own ads, not when I Favourite, other peopl's Ads)

**Comment by sudiptaExicube** [comment]
Solved, Will Be Updated in Next Release.

**Comment by spunlock** [comment]
Solved, Thanks !
