### ISSUE TITLE
N12. Shop listings by category : how can we find Sub-Categories ? better show a page, where all categories are displayed, and if a category has sub-categories, when we click on it, it should show the sub-categories page (Please put categories icons placeholder image, I will give you list of icons to replace with)

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#8]
#how can we find Sub-Categories ?

 it is already done please view bellow screen shot
![capture](https://user-images.githubusercontent.com/20201253/36374955-42c0c612-1593-11e8-8cde-753149bd7a97.PNG)

 (Please put categories icons placeholder image, I will give you list of icons to replace with) -- 
where is the icon list  and sub categori list??

**Comment by spunlock** [comment]
I didnt say "Filter" listings by Sub Categories, I said "Shop" listings, means discovering listings inside a particular sub category. 
It should be straight forward, and not assuming that the user, will know that he should go to Parent Category, then hits Filter, then scolls down, to where Sub-Category filter list is added, to discover ads inside that sub-category.  

This is the flow I suggest, 

When we click on the "Pointing down arrow",

**Comment by spunlock** [comment]
![n12-1](https://user-images.githubusercontent.com/11454643/36822444-587072fc-1cf8-11e8-932a-4c80e27f38f4.gif)

**Comment by spunlock** [comment]
We'll see the Parent Categories, all in one page, (with icons relevant to each category at the left, 
with a Arrow on each line at the right, sending to Sub / Categories)

**Comment by spunlock** [comment]
![n12-2](https://user-images.githubusercontent.com/11454643/36822517-bfd9a5c6-1cf8-11e8-8e6f-8ed4108d13f4.gif)

**Comment by spunlock** [comment]
Notice that inside the page where there are Sub-categories, I can choose to see **All Ads** inside the Parent Category, by selecting the first item in the list

**Comment by spunlock** [comment]
![n12-3](https://user-images.githubusercontent.com/11454643/36822546-e78ef8a0-1cf8-11e8-813e-0dc6284d2721.gif)

**Comment by spunlock** [comment]
Hello, 
Can't you make this Layout, instead of the tiny drop down popup list, of categories ?

**Comment by spunlock** [comment]
Not done as desired pattern, but I'll close this for now
