### ISSUE TITLE
N13. Use Digit Keyboard, for Price fields  (Set Ad price / Filter Ads)

### ISSUE THREAD

**Issue by sudiptaExicube** [codersudipta/EcomIssues#9]
It Already Done please view bellow screen shots

![sss](https://user-images.githubusercontent.com/20201253/36375513-8d5f63a2-1595-11e8-81a9-8e36b113dc81.png)

![screenshot_20180219-165010](https://user-images.githubusercontent.com/20201253/36375484-6edf608a-1595-11e8-9e3a-6a015f656647.png)

**Comment by spunlock** [comment]
I'm using an iPhone, and its only working on Make Offer field, see below :  

![img_2528](https://user-images.githubusercontent.com/11454643/36536932-f044e394-17ce-11e8-9d2e-bbc45306df8b.PNG)


![img_2529](https://user-images.githubusercontent.com/11454643/36536933-f069466c-17ce-11e8-881c-c3607f53e236.PNG)


![img_2530](https://user-images.githubusercontent.com/11454643/36536935-f08ccbdc-17ce-11e8-9a72-8e8a92066470.PNG)

**Comment by spunlock** [comment]
Very good, Thanks !
